title: Penalty Kicks in Professional Soccer
description: This project explores the role and influence of penalty kicks in professional soccer. Drawing on data from several top-tier and second-tier leagues around the world, the analysis aims to quantify how penalty kicks affect match outcomes, league standings, and individual scoring achievements.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
